@startuml

skinparam backgroundColor White
skinparam shadowing false
skinparam defaultFontColor Black
skinparam ArrowColor Black

skinparam activity {
    BackgroundColor White
    BorderColor Black
    FontColor Black
    DiamondBackgroundColor White
    DiamondBorderColor Black
    DiamondFontColor Black
    StartColor Black
    EndColor Black
    BarColor Black
}

title Proses Analitik Pemakaian dan Pengelolaan Iuran

|#White|Pengurus|
start

:Mengakses dashboard
pemakaian komunal;

|#White|Sistem|
:Mengambil data pemakaian
air dan energi;

:Mengolah data
pemakaian komunal;

:Menampilkan dashboard
analitik;

|#White|Pengurus|
:Menganalisis data
pemakaian;

:Mengakses pengelolaan
iuran warga;

|#White|Sistem|
:Menampilkan data
pemakaian bulanan;

|#White|Pengurus|
:Mengkalkulasi
iuran warga;

:Menetapkan tagihan
iuran bulanan;

|#White|Sistem|
:Menyimpan hasil
kalkulasi iuran;

:Membuat rincian tagihan
masing-masing warga;

|#White|Warga|
:Mengakses menu
tagihan;

|#White|Sistem|
:Menampilkan rincian
tagihan iuran;

|#White|Warga|
:Melihat rincian
tagihan bulanan;

|#White|Pengurus|
:Memilih pembuatan
rekapitulasi;

|#White|Sistem|
:Mengolah data pemakaian
dan iuran bulanan;

:Mengekspor rekapitulasi
laporan;

|#White|Pengurus|
:Mengakses hasil
rekapitulasi;

stop

@enduml