@startuml

skinparam backgroundColor White
skinparam shadowing false
skinparam defaultFontColor Black
skinparam ArrowColor Black

skinparam activity {
    BackgroundColor White
    BorderColor Black
    FontColor Black
    DiamondBackgroundColor White
    DiamondBorderColor Black
    DiamondFontColor Black
    StartColor Black
    EndColor Black
    BarColor Black
}

title Proses Pemantauan Air dan Energi oleh Warga

|#White|Warga|
start

:Mengakses halaman
pemantauan;

|#White|Sistem|
:Memuat data kondisi
infrastruktur;

:Menampilkan ketersediaan
air tangki;

:Menampilkan status daya
panel surya dan baterai;

|#White|Warga|
:Melihat ketersediaan air;

:Melihat kondisi
pasokan daya;

stop

@enduml